exclude: ["CNAME", "Gemfile", "Gemfile.lock", "jekyll-theme-hydeout.gemspec", "README.md"]

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            SyGuS
tagline:          
description:      'Syntax-Guided Synthesis'
url:              https://sygus.org
baseurl:          
permalink:        pretty

author:
  name:           'Saswat Padhi'
  url:            https://saswatpadhi.github.io

# Configuration
sidebar_home_link:  false
